# ArgoCD Application for GitOps deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auchitya-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/auchitya-cloud/CRMservices
    targetRevision: main
    path: OrderMicroservice/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: auchitya-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
